# Generated by Django 2.2.5 on 2019-09-14 03:48

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_auto_20190907_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecolumn',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='articles_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
